
import 'country.dart';

final List<Country> countryList = [
  Country('Afghanistan', '+93', 'AF', 'af.svg'),
  Country('Albania', '+355', 'AL', 'al.svg'),
  Country('Algeria', '+213', 'DZ', 'dz.svg'),
  Country('American Samoa', '+1 684', 'AS', 'as.svg'),
  Country('Andorra', '+376', 'AD', 'ad.svg'),
  Country('Angola', '+244', 'AO', 'ao.svg'),
  Country('Anguilla', '+1 264', 'AI', 'ai.svg'),
  Country('Antigua and Barbuda', '+1 268', 'AG', 'ag.svg'),
  Country('Argentina', '+54', 'AR', 'ar.svg'),
  Country('Armenia', '+374', 'AM', 'am.svg'),
  Country('Aruba', '+297', 'AW', 'aw.svg'),
  Country('Australia', '+61', 'AU', 'au.svg'),
  Country('Austria', '+43', 'AT', 'at.svg'),
  Country('Azerbaijan', '+994', 'AZ', 'az.svg'),
  Country('Bahamas', '+1 242', 'BS', 'bs.svg'),
  Country('Bahrain', '+973', 'BH', 'bh.svg'),
  Country('Bangladesh', '+880', 'BD', 'bd.svg'),
  Country('Barbados', '+1 246', 'BB', 'bb.svg'),
  Country('Belarus', '+375', 'BY', 'by.svg'),
  Country('Belgium', '+32', 'BE', 'be.svg'),
  Country('Belize', '+501', 'BZ', 'bz.svg'),
  Country('Benin', '+229', 'BJ', 'bj.svg'),
  Country('Bermuda', '+1 441', 'BM', 'bm.svg'),
  Country('Bhutan', '+975', 'BT', 'bt.svg'),
  Country('Bolivia', '+591', 'BO', 'bo.svg'),
  Country('Bosnia and Herzegovina', '+387', 'BA', 'ba.svg'),
  Country('Botswana', '+267', 'BW', 'bw.svg'),
  Country('Brazil', '+55', 'BR', 'br.svg'),
  Country('British Indian Ocean Territory', '+246', 'IO', 'io.svg'),
  Country('British Virgin Islands', '+1 284', 'VG', 'vg.svg'),
  Country('Brunei', '+673', 'BN', 'bn.svg'),
  Country('Bulgaria', '+359', 'BG', 'bg.svg'),
  Country('Burkina Faso', '+226', 'BF', 'bf.svg'),
  Country('Burundi', '+257', 'BI', 'bi.svg'),
  Country('Cambodia', '+855', 'KH', 'kh.svg'),
  Country('Cameroon', '+237', 'CM', 'cm.svg'),
  Country('Canada', '+1', 'CA', 'ca.svg'),
  Country('Cape Verde', '+238', 'CV', 'cv.svg'),
  Country('Cayman Islands', '+ 345', 'KY', 'ky.svg'),
  Country('Central African Republic', '+236', 'CF', 'cf.svg'),
  Country('Chad', '+235', 'TD', 'td.svg'),
  Country('Chile', '+56', 'CL', 'cl.svg'),
  Country('China', '+86', 'CN', 'cn.svg'),
  Country('Christmas Island', '+61', 'CX', 'cx.svg'),
  Country('Colombia', '+57', 'CO', 'co.svg'),
  Country('Comoros', '+269', 'KM', 'km.svg'),
  Country('Congo', '+242', 'CG', 'cg.svg'),
  Country('Congo, Dem. Rep. of Country(Zaire)', '+243', 'CD', 'cd.svg'),
  Country('Cook Islands', '+682', 'CK', 'ck.svg'),
  Country('Costa Rica', '+506', 'CR', 'cr.svg'),
  Country('Croatia', '+385', 'HR', 'hr.svg'),
  Country('Cuba', '+53', 'CU', 'cu.svg'),
  Country('Curacao', '+599', 'CW', 'cw.svg'),
  Country('Cyprus', '+537', 'CY', 'cy.svg'),
  Country('Czech Republic', '+420', 'CZ', 'cz.svg'),
  Country('Denmark', '+45', 'DK', 'dk.svg'),
  Country('Djibouti', '+253', 'DJ', 'dj.svg'),
  Country('Dominica', '+1 767', 'DM', 'dm.svg'),
  Country('Dominican Republic', '+1 809', 'DO', 'do.svg'),
  Country('East Timor', '+670', 'TR', 'tr.svg'),
  Country('Ecuador', '+593', 'EC', 'ec.svg'),
  Country('Egypt', '+20', 'EG', 'eg.svg'),
  Country('El Salvador', '+503', 'SV', 'sv.svg'),
  Country('Equatorial Guinea', '+240', 'GQ', 'gq.svg'),
  Country('Eritrea', '+291', 'ER', 'er.svg'),
  Country('Estonia', '+372', 'EE', 'ee.svg'),
  Country('Ethiopia', '+251', 'ET', 'et.svg'),
  Country('Falkland Islands', '+500', 'FK', 'fk.svg'),
  Country('Faroe Islands', '+298', 'FO', 'fo.svg'),
  Country('Fiji', '+679', 'FJ', 'fj.svg'),
  Country('Finland', '+358', 'FI', 'fi.svg'),
  Country('France', '+33', 'FR', 'fr.svg'),
  Country('French Guiana', '+594', 'GF', 'gf.svg'),
  Country('French Polynesia', '+689', 'PF', 'pf.svg'),
  Country('Gabon', '+241', 'GA', 'ga.svg'),
  Country('Gambia', '+220', 'GM', 'gm.svg'),
  Country('Georgia', '+995', 'GE', 'ge.svg'),
  Country('Germany', '+49', 'DE', 'de.svg'),
  Country('Ghana', '+233', 'GH', 'gh.svg'),
  Country('Gibraltar', '+350', 'GI', 'gi.svg'),
  Country('Greece', '+30', 'GR', 'gr.svg'),
  Country('Greenland', '+299', 'GL', 'gl.svg'),
  Country('Grenada', '+1 473', 'GD', 'gd.svg'),
  Country('Guadeloupe', '+590', 'GP', 'gp.svg'),
  Country('Guam', '+1 671', 'GU', 'gu.svg'),
  Country('Guatemala', '+502', 'GT', 'gt.svg'),
  Country('Guinea', '+224', 'GN', 'gn.svg'),
  Country('Guinea-Bissau', '+245', 'GW', 'gw.svg'),
  Country('Guyana', '+595', 'GY', 'gy.svg'),
  Country('Haiti', '+509', 'HT', 'ht.svg'),
  Country('Honduras', '+504', 'HN', 'hn.svg'),
  Country('Hong Kong', '+852', 'HK', 'hk.svg'),
  Country('Hungary', '+36', 'HU', 'hu.svg'),
  Country('Iceland', '+354', 'IS', 'is.svg'),
  Country('India', '+91', 'IN', 'in.svg'),
  Country('Indonesia', '+62', 'ID', 'id.svg'),
  Country('Iran', '+98', 'IR', 'ir.svg'),
  Country('Iraq', '+964', 'IQ', 'iq.svg'),
  Country('Ireland', '+353', 'IE', 'ie.svg'),
  Country('Israel', '+972', 'IL', 'il.svg'),
  Country('Italy', '+39', 'IT', 'it.svg'),
  Country('Ivory Coast', '+225', 'CI', 'ci.svg'),
  Country('Jamaica', '+1 876', 'JM', 'jm.svg'),
  Country('Japan', '+81', 'JP', 'jp.svg'),
  Country('Jordan', '+962', 'JO', 'jo.svg'),
  Country('Kazakhstan', '+7 7', 'KZ', 'kz.svg'),
  Country('Kenya', '+254', 'KE', 'ke.svg'),
  Country('Kiribati', '+686', 'KI', 'ki.svg'),
  Country('Kuwait', '+965', 'KW', 'kw.svg'),
  Country('Kyrgyzstan', '+996', 'KG', 'kg.svg'),
  Country('Laos', '+856', 'LA', 'la.svg'),
  Country('Latvia', '+371', 'LV', 'lv.svg'),
  Country('Lebanon', '+961', 'LB', 'lb.svg'),
  Country('Lesotho', '+266', 'LS', 'ls.svg'),
  Country('Liberia', '+231', 'LR', 'lr.svg'),
  Country('Libya', '+218', 'LY', 'ly.svg'),
  Country('Liechtenstein', '+423', 'LI', 'li.svg'),
  Country('Lithuania', '+370', 'LT', 'lt.svg'),
  Country('Luxembourg', '+352', 'LU', 'lu.svg'),
  Country('Macau', '+853', 'MO', 'mo.svg'),
  Country('Macedonia', '+389', 'MK', 'mk.svg'),
  Country('Madagascar', '+261', 'MG', 'mg.svg'),
  Country('Malawi', '+265', 'MW', 'mw.svg'),
  Country('Malaysia', '+60', 'MY', 'my.svg'),
  Country('Maldives', '+960', 'MV', 'mv.svg'),
  Country('Mali', '+223', 'ML', 'ml.svg'),
  Country('Malta', '+356', 'MT', 'mt.svg'),
  Country('Marshall Islands', '+692', 'MH', 'mh.svg'),
  Country('Martinique', '+596', 'MQ', 'mq.svg'),
  Country('Mauritania', '+222', 'MR', 'mr.svg'),
  Country('Mauritius', '+230', 'MU', 'mu.svg'),
  Country('Mayotte', '+262', 'YT', 'yt.svg'),
  Country('Mexico', '+52', 'MX', 'mx.svg'),
  Country('Micronesia', '+691', 'FM', 'fm.svg'),
  Country('Moldova', '+373', 'MD', 'md.svg'),
  Country('Monaco', '+377', 'MC', 'mc.svg'),
  Country('Mongolia', '+976', 'MN', 'mn.svg'),
  Country('Montenegro', '+382', 'ME', 'me.svg'),
  Country('Montserrat', '+1664', 'MS', 'ms.svg'),
  Country('Morocco', '+212', 'MA', 'ma.svg'),
  Country('Myanmar', '+95', 'MM', 'mm.svg'),
  Country('Namibia', '+264', 'NA', 'na.svg'),
  Country('Nauru', '+674', 'NR', 'nr.svg'),
  Country('Nepal', '+977', 'NP', 'np.svg'),
  Country('Netherlands', '+31', 'NL', 'nl.svg'),
  Country('Saint Kitts and Nevis', '+1', 'KN', 'kn.svg'),
  Country('New Caledonia', '+687', 'NC', 'nc.svg'),
  Country('New Zealand', '+64', 'NZ', 'nz.svg'),
  Country('Nicaragua', '+505', 'NI', 'ni.svg'),
  Country('Niger', '+227', 'NE', 'ne.svg'),
  Country('Nigeria', '+234', 'NG', 'ng.svg'),
  Country('Niue', '+683', 'NU', 'nu.svg'),
  Country('Norfolk Island', '+672', 'NF', 'nf.svg'),
  Country('North Korea', '+850', 'KP', 'kp.svg'),
  Country('Northern Mariana Islands', '+1 670', 'MP', 'mp.svg'),
  Country('Norway', '+47', 'NO', 'no.svg'),
  Country('Oman', '+968', 'OM', 'om.svg'),
  Country('Pakistan', '+92', 'PK', 'pk.svg'),
  Country('Palau', '+680', 'PW', 'pw.svg'),
  Country('Panama', '+507', 'PA', 'pa.svg'),
  Country('Papua New Guinea', '+675', 'PG', 'pg.svg'),
  Country('Paraguay', '+595', 'PY', 'py.svg'),
  Country('Peru', '+51', 'PE', 'pe.svg'),
  Country('Philippines', '+63', 'PH', 'ph.svg'),
  Country('Poland', '+48', 'PL', 'pl.svg'),
  Country('Portugal', '+351', 'PT', 'pt.svg'),
  Country('Puerto Rico', '+1 787', 'PR', 'pr.svg'),
  Country('Qatar', '+974', 'QA', 'qa.svg'),
  Country('Reunion', '+262', 'RE', 're.svg'),
  Country('Romania', '+40', 'RO', 'ro.svg'),
  Country('Russia', '+7', 'RU', 'ru.svg'),
  Country('Rwanda', '+250', 'RW', 'rw.svg'),
  Country('Samoa', '+685', 'WS', 'ws.svg'),
  Country('San Marino', '+378', 'SM', 'sm.svg'),
  Country('Saudi Arabia', '+966', 'SA', 'sa.svg'),
  Country('Senegal', '+221', 'SN', 'sn.svg'),
  Country('Serbia', '+381', 'RS', 'rs.svg'),
  Country('Seychelles', '+248', 'SC', 'sc.svg'),
  Country('Sierra Leone', '+232', 'SL', 'sl.svg'),
  Country('Singapore', '+65', 'SG', 'sg.svg'),
  Country('Slovakia', '+421', 'SK', 'sk.svg'),
  Country('Slovenia', '+386', 'SI', 'si.svg'),
  Country('Solomon Islands', '+677', 'SB', 'sb.svg'),
  Country('South Africa', '+27', 'ZA', 'za.svg'),
  Country(
      'South Georgia and the South Sandwich Islands', '+500', 'GS', 'gs.svg'),
  Country('South Korea', '+82', 'KR', 'kr.svg'),
  Country('Spain', '+34', 'ES', 'es.svg'),
  Country('Sri Lanka', '+94', 'LK', 'lk.svg'),
  Country('Sudan', '+249', 'SD', 'sd.svg'),
  Country('Suriname', '+597', 'SR', 'sr.svg'),
  Country('Swaziland', '+268', 'SZ', 'sz.svg'),
  Country('Sweden', '+46', 'SE', 'se.svg'),
  Country('Switzerland', '+41', 'CH', 'ch.svg'),
  Country('Syria', '+963', 'SY', 'sy.svg'),
  Country('Taiwan', '+886', 'TW', 'tw.svg'),
  Country('Tajikistan', '+992', 'TJ', 'tj.svg'),
  Country('Tanzania', '+255', 'TZ', 'tz.svg'),
  Country('Thailand', '+66', 'TH', 'th.svg'),
  Country('Timor Leste', '+670', 'TL', 'tl.svg'),
  Country('Togo', '+228', 'TG', 'tg.svg'),
  Country('Tokelau', '+690', 'TK', 'tk.svg'),
  Country('Tonga', '+676', 'TO', 'to.svg'),
  Country('Trinidad and Tobago', '+1 868', 'TT', 'tt.svg'),
  Country('Tunisia', '+216', 'TN', 'tn.svg'),
  Country('Turkey', '+90', 'TR', 'tr.svg'),
  Country('Turkmenistan', '+993', 'TM', 'tm.svg'),
  Country('Turks and Caicos Islands', '+1 649', 'TC', 'tc.svg'),
  Country('Tuvalu', '+688', 'TV', 'tv.svg'),
  Country('Uganda', '+256', 'UG', 'ug.svg'),
  Country('Ukraine', '+380', 'UA', 'ua.svg'),
  Country('United Arab Emirates', '+971', 'AE', 'ae.svg'),
  Country('United Kingdom', '+44', 'GB', 'gb.svg'),
  Country('United States', '+1', 'US', 'us.svg'),
  Country('Uruguay', '+598', 'UY', 'uy.svg'),
  Country('Uzbekistan', '+998', 'UZ', 'uz.svg'),
  Country('Vanuatu', '+678', 'VU', 'vu.svg'),
  Country('Venezuela', '+58', 'VE', 've.svg'),
  Country('Vietnam', '+84', 'VN', 'vn.svg'),
  Country('Wallis and Futuna', '+681', 'WF', 'wf.svg'),
  Country('Yemen', '+967', 'YE', 'ye.svg'),
  Country('Zambia', '+260', 'ZM', 'zm.svg'),
  Country('Zimbabwe', '+263', 'ZW', 'zw.svg'),
];

// void Country(String name, String phCode, String code, String flag) {
//   country.add(Country(name, phCode, code, flag)),
// }
